app/user/views.py
from flask import redirect, request, jsonify, Blueprint, session, render_template, url_for
import bcrypt
from app.user.models import User
from app.user.forms import RegisterForm, LoginForm

user_bp = Blueprint('user', __name__, url_prefix='/user/')
def gen_pass(passw):
    salt = bcrypt.gensalt()
    return bcrypt.hashpw(passw.encode('utf-8'), salt)

def start_session(user):
    user = user.asdict()
    session['logged_in'] = True
    session['user'] = user
    return redirect(url_for('home'))


@user_bp.route('/entrar/', methods=["GET", "POST"])
def signin():
    lform = LoginForm()
    if request.method == "POST" and lform.validate():
        email = lform.email.data
        password = lform.password.data
        user = User.objects(email=email).first()
        if user and bcrypt.checkpw(password.encode('utf-8'), user.password):
            return start_session(user)
    return render_template('login.html', lform=lform, page_name="Login - CV SECURITY")

@user_bp.route('/cadastrar/', methods=['GET', 'POST'])
def signup():
    sform = RegisterForm()
    if request.method == 'POST' and sform.validate():
        username = sform.name.data
        email = sform.email.data
        password = sform.password.data

        password = gen_pass(password)

        user = User(
            username=username,
            email=email,
            password=password
        )
        
        user.save()

        return start_session(user)

    return render_template('signup.html', sform=sform, page_name="Cadastro - CV SECURITY")

@user_bp.route('/signout/')
def signout():
    session.clear()
    return redirect('/')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{page_name}}</title>
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/icons/bootstrap-icons/font/bootstrap-icons.min.css">
    {% block styles %}
    {% endblock %}
</head>
<body>
    {% block content %}

    {% endblock %}
    <script src="/static/js/bootstrap.min.js"></script>
    {% block scripts %}
    {% endblock %}
</body>
</html>

app/templates/camera.html
{% extends "menu_footer.html" %}

{% block styles %}
    <link rel="stylesheet" href="{{url_for('static', filename='css/test.css')}}">
{% endblock %}

{% block scripts %}
    {%if session.user['is_admin']%}
    <script type="module" src="{{url_for('static', filename='js/camera_admin.js')}}"></script>
    {%else%}
    <p>{{edit}}</p>
    <script type="module" src="{{url_for('static', filename='js/camera.js')}}"></script>
    {%endif%}
{% endblock %}

{% block page_content %}
    <div class="card mx-auto mt-4 report--card mb-4" style="min-width: 200px; max-width: 1000px; width: 80%;">
        <div class="card-header d-flex justify-content-between">
            <a class="report--link" href="#">Câmera monitorada</a>
            {%if session.user['is_admin']%}
                <button id="cleanButton" type="button" class="report--link d-inline btn btn-link py-0" href="#"> <i class="bi bi-arrow-clockwise"></i> LIMPAR</button>
            {%endif%}
        </div>
        <div class="card-body">
            <div class="mx-auto" id="svgc"></div>
        </div>
    </div>
{%endblock%}

app/templates/home.html
{% extends "menu_footer.html" %}

{% block scripts %}
    <script src="/static/js/home.js"></script>
{% endblock %}

{% block page_content %}
    <div class="card mx-auto mt-4 report--card mb-4" style="min-width: 200px; max-width: 1000px; width: 80%;">
        <div class="card-header"><a class="report--link" href="#">ÚLTIMA ENTRADA | Atualização em tempo real</a></div>
        <div class="card-body">
          <h4 id="report-data" class="card-title">detecção em</h4>
          <ul>
            <li id="report-local">Local:</li>
            <li id="report-hora">Hora:</li>
          </ul>
        <div class="flex mx-auto" style="width: 80%">
          <img id="report-img" class="img-fluid" style="max-width: 100%;">
        </div>
        </div>
    </div>
{%endblock%}

app/templates/login.html
{% extends "base.html" %}
{% block content %}
    <div class="cardw-wrapper">
        <div class="cardw">
            <form name="login_form" method="POST">
              {{lform.csrf_token}}
              {%if lform.errors%}
                <fieldset>
                  <legend>Entre</legend>
                  <div class="form-group has-danger">
                    {{lform.email.label(class_="form-label mt-4")}}
                    {{lform.email(class_="form-control mb-3 is-invalid", placeholder="exemplo@email.com")}}
                  </div>
                  <div class="form-group has-danger">
                    {{lform.password.label(class_="form-label mt-2")}}
                    {{lform.password(class_="form-control is-invalid", type="password", placeholder="*"*8)}}
                    <div class="invalid-feedback pb-0 mb-0">{{lform.errors['password'][0]}}</div>
                  </div>
                  <button type="submit" class="btn btn-primary mt-4">Entrar</button>
                </fieldset>
              {%else%}
                <fieldset>
                  <legend>Entre</legend>
                  <div class="form-group">
                    {{lform.email.label(class_="form-label mt-4")}}
                    {{lform.email(class_="form-control mb-3", type="email", placeholder="exemplo@email.com")}}
                  </div>
                  <div class="form-group">
                    {{lform.password.label(class_="form-label mt-2")}}
                    {{lform.password(type="password", class_="form-control", placeholder="*"*8)}}
                  </div>
                  <button type="submit" class="btn btn-primary mt-4">Entrar</button>
                </fieldset>
              {%endif%}
          </form>
          <div class="pt-4">
            <a href={{url_for("user.signup")}}>Não tem uma conta?</p>
          </div>
        </div> 
    </div> 
{% endblock %}

app/templates/menu_footer.html
{% extends "base.html" %}

{% block content %}
<div class="d-flex flex-column min-vh-100 base-container">
    <nav class="navbar navbar-expand-lg bg-primary p-1" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">CV-Security</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarColor01">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link {{navclass.get('home', '')}}" href={{url_for('home')}}>Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {{navclass.get('camera', '')}}" href={{url_for('camera')}}>Câmera</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {{navclass.get('relatorios', '')}}" href={{url_for('relatorios')}}>Relatórios</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {{navclass.get('sair', '')}}" href={{url_for("user.signout")}}>Sair</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
  {% block page_content %}

  {% endblock %}
    <footer class="text-center text-lg-start bg-white text-muted">
      <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.025);">
    </div>
  </footer>
</div>
  {% endblock %}

app/templates/relatorios.html
{%extends "menu_footer.html"%}

{% block scripts %}
    <script src="/static/js/relatorios.js"></script>
{% endblock %}

{%block page_content%}
  <div id='modal' class="modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">ATENÇÃO</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"></span>
          </button>
        </div>
        <div class="modal-body">
          <p class="text-justify text-break"></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary modal_delete">Deletar</button>
          <button type="button" class="btn btn-secondary modal_cancel" data-bs-dismiss="modal">Cancelar</button>
        </div>
      </div>
    </div>
  </div>
  <div class="mt-4" sytle="width: 300px;">
    <table class="table table-hover mx-auto pt-3" style="width: 65%; box-shadow: 0 8px 26px -4px rgba(79, 71, 71, 0.15); text-align: center;">
        <thead>
          <tr>
            <th scope="col">Data</th>
            <th scope="col">Local</th>
            <th scope="col">Image_URL</th>
          </tr>
        </thead>
        {% for i in range(n_rows) %}
            {% if i%2==0 %}
            <tr class="table-primary rlist" id="{{images[i]}}">
            {% else %}
            <tr class="table-default rlist" id="{{images[i]}}">
            {% endif %}
            <th scope="row" class="table_date">{{dates[i]}}</th>
            <td>{{locals[i]}}</td>
            <td>{{images[i]}}</td>
            {%if session['user']['is_admin']%}
            <td><button class="invisible btn float-left"><i class="delete_item bi bi-trash"></i></button></td>
            {%endif%}
            </tr>
        {% endfor %}
      </table>
      {%if session['user']['is_admin']%}
      <div class="mb-3" style="display: flex; justify-content: center; font-size: 15px;">
        <button class="btn" id="delete_all">
          <i class="bi bi-folder-x"> APAGAR TUDO</i>
        </button>
      </div>
      {%endif%}
      <div class="mx-auto" style="display: flex; justify-content: center; font-size: 15px;">
       <ul class="pagination">
         {% if current_page == 1 %}
          <li class="page-item disabled">
         {% else %}
          <li class="page-item">
         {% endif %}
            <a class="page-link" href={{url_for("relatorios", page=1)}}>&laquo;</a>
          </li>
          {% for i in range(n_indexes) %}
            {% if pages[i] == current_page %}
            <li class="page-item active">
            {% else %}
            <li class="page-item">
            {% endif %}
            <a class="page-link" href={{url_for("relatorios", page=pages[i])}}>{{pages[i]}}</a>
            </li>
          {% endfor %}
          {% if current_page == total_pages %}
          <li class="page-item disabled">
          {% else %}
          <li class="page-item">
          {% endif %}
            <a class="page-link" href={{url_for("relatorios", page=total_pages)}}>&raquo;</a>
          </li>
        </ul>
        </div>
</div>
{%endblock%}

app/templates/signup.html
{% extends "base.html" %}
{% block content %}
    <div class="cardw-wrapper">
        <div class="cardw">
            <form name="singup_form" method="POST">
                {{sform.csrf_token}}
                <fieldset>
                  <legend>Cadastre-se</legend>
                  <div class="form-group">
                    {{sform.name.label(class_="form-label mt-4")}}
                    {{sform.name(class_="form-control", placeholder="João da Silva")}}
                  </div>
                  {%if sform.errors.get('email')%}
                      <div class="form-group has-danger">
                        {{sform.email.label(class_="form-label mt-4")}}
                        {{sform.email(class_="form-control is-invalid", type="email", placeholder="exemplo@email.com")}}
                        <div class="invalid-feedback">{{ sform.errors['email'][0] }}</div>
                      </div>
                  {%else%}
                      <div class="form-group">
                        {{sform.email.label(class_="form-label mt-4")}}
                        {{sform.email(class_="form-control", type="email", placeholder="exemplo@email.com")}}
                      </div>
                  {%endif%}
                  <div class="form-group">
                    {{sform.password.label(class_="form-label mt-4")}}
                    {{sform.password(class_="form-control mb-3", placeholder="*"*8)}}
                  </div>
                  <button type="submit" class="btn btn-primary">Cadastrar</button>
                </fieldset>
          </form>
          <div class="pt-4">
            <a href={{url_for("user.signin")}}>Realizar Log-In em vez disso</p>
          </div>
        </div> 
        </div> 
    </div> 
{% endblock %}